- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.3 state=latest update_cache=true
  ignore_errors: yes

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf

- name: Restart PostgreSQL
  command: service postgresql restart

# por algum motivo isso aqui não pegou
# por algum motivo isso aqui pegou depois
- name: create the postgresql user for application
  postgresql_user: name={{ ruby_deploy_user }}
  sudo: yes
  sudo_user: postgres
  tags: postgres_create_user

- name: create the postgresql database for application
  postgresql_db: name={{app_name}} owner={{ ruby_deploy_user }} state=present
  sudo: yes
  sudo_user: postgres
  tags: postgres_create_table
